#!/bin/sh
# Install the built Linux ARM64 executable for the current user and generate a
# matching uninstaller beside this script. No system directories are changed.
set -eu

usage()
{
  echo "Usage: $0 [--install-dir ABSOLUTE_DIRECTORY]" >&2
}

if [ "$#" -eq 0 ]; then
  if [ -z "${HOME:-}" ]; then
    echo "Error: HOME is required when --install-dir is omitted." >&2
    exit 1
  fi
  install_dir="$HOME/.local/bin"
elif [ "$#" -eq 2 ] && [ "$1" = "--install-dir" ]; then
  install_dir="$2"
else
  usage
  exit 1
fi

case "$install_dir" in
  /*) ;;
  *)
    echo "Error: --install-dir must be an absolute path: $install_dir" >&2
    exit 1
    ;;
esac

# Paths are embedded as single-quoted values in the generated shell script.
# Reject a quote rather than generating text which could be interpreted as code.
case "$install_dir" in
  *"'"*)
    echo "Error: --install-dir cannot contain a single quote." >&2
    exit 1
    ;;
esac

if [ "$(uname -s)" != "Linux" ] || [ "$(uname -m)" != "aarch64" ]; then
  echo "Error: this installer supports only Linux on ARM64." >&2
  exit 1
fi

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
case "$script_dir" in
  *"'"*)
    echo "Error: the installer path cannot contain a single quote." >&2
    exit 1
    ;;
esac
repo_root=$(dirname "$script_dir")
artifact="$repo_root/artifacts/aec-linux-arm64/aec"
target="$install_dir/aec"
uninstaller="$script_dir/uninstall-aec-linux-arm64.sh"
uninstaller_marker='# AEC generated Linux ARM64 uninstaller version=1'

# Refuse a linked install directory or linked existing ancestor. Otherwise an
# apparently personal destination could redirect writes outside the chosen path.
path_to_check=$install_dir
while [ "$path_to_check" != / ]; do
  if [ -L "$path_to_check" ]; then
    echo "Error: install directory path cannot contain a symbolic link: $path_to_check" >&2
    exit 1
  fi
  path_to_check=$(dirname "$path_to_check")
done
if [ -e "$install_dir" ] && [ ! -d "$install_dir" ]; then
  echo "Error: install directory must be absent or a directory: $install_dir" >&2
  exit 1
fi

if [ ! -f "$artifact" ] || [ ! -x "$artifact" ] || [ -L "$artifact" ]; then
  echo "Error: build artifact is missing or unsafe: $artifact" >&2
  echo "Run $repo_root/scripts/build-linux-arm64.sh first." >&2
  exit 1
fi
if ! command -v sha256sum >/dev/null 2>&1; then
  echo "Error: sha256sum is required to install aec." >&2
  exit 1
fi
if ! "$artifact" version >/dev/null 2>&1; then
  echo "Error: build artifact failed its version check: $artifact" >&2
  exit 1
fi

if [ -L "$target" ] || { [ -e "$target" ] && [ ! -f "$target" ]; }; then
  echo "Error: install target must be absent or a regular file: $target" >&2
  exit 1
fi
if [ -L "$uninstaller" ] || { [ -e "$uninstaller" ] && [ ! -f "$uninstaller" ]; }; then
  echo "Error: generated uninstaller must be absent or a regular file: $uninstaller" >&2
  exit 1
fi
if [ -f "$uninstaller" ] && ! grep -Fqx "$uninstaller_marker" "$uninstaller"; then
  echo "Error: Refusing to overwrite non-AEC uninstaller: $uninstaller" >&2
  exit 1
fi

if [ -z "${HOME:-}" ] || [ "$install_dir" != "$HOME/.local/bin" ]; then
  printf 'warning: custom AEC install directory: %s\n' "$install_dir" >&2
  printf '%s\n' 'The $aec skill invokes `aec` through PATH.' >&2
  printf '%s\n' 'Ensure this directory is available to Codex, restart Codex, then run `aec help`.' >&2
fi

artifact_hash=$(sha256sum "$artifact")
artifact_hash=${artifact_hash%% *}
uninstaller_temporary=$(mktemp "$script_dir/.uninstall-aec-linux-arm64.XXXXXX")
binary_temporary=
cleanup()
{
  [ -z "${binary_temporary:-}" ] || rm -f -- "$binary_temporary"
  [ -z "${uninstaller_temporary:-}" ] || rm -f -- "$uninstaller_temporary"
}
trap cleanup 0
trap 'cleanup; exit 1' HUP INT TERM

# Embed the exact managed paths and digest. The helper refuses copied execution
# or a replaced binary before it changes any Codex runtime state.
{
  printf '%s\n' '#!/bin/sh' "$uninstaller_marker"
  printf '%s\n' '# This file was generated by install-linux-arm64.sh. Do not edit it.'
  printf "installed_aec='%s'\n" "$target"
  printf "installed_aec_hash='%s'\n" "$artifact_hash"
  printf "installed_uninstaller='%s'\n" "$uninstaller"
  cat <<'EOF'
set -eu

usage()
{
  echo "Usage: $0 [--codex-home ABSOLUTE_PATH]" >&2
}

codex_home=
if [ "$#" -eq 0 ]; then
  :
elif [ "$#" -eq 2 ] && [ "$1" = "--codex-home" ] && [ -n "$2" ]; then
  codex_home="$2"
  case "$codex_home" in
    /*) ;;
    *)
      echo "Error: --codex-home must be an absolute path: $codex_home" >&2
      exit 1
      ;;
  esac
else
  usage
  exit 1
fi

case "$0" in
  */*) ;;
  *)
    echo "Error: run this uninstaller by its explicit path." >&2
    exit 1
    ;;
esac
script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
script_path="$script_dir/$(basename -- "$0")"
if [ "$script_path" != "$installed_uninstaller" ]; then
  echo "Error: run the uninstaller from its generated path: $installed_uninstaller" >&2
  exit 1
fi

if [ ! -f "$installed_aec" ] || [ ! -x "$installed_aec" ] || [ -L "$installed_aec" ]; then
  echo "Error: installed aec executable is missing or unsafe: $installed_aec" >&2
  exit 1
fi
actual_hash=$(sha256sum "$installed_aec")
actual_hash=${actual_hash%% *}
if [ "$actual_hash" != "$installed_aec_hash" ]; then
  echo "Error: installed aec executable differs from the installed artifact." >&2
  exit 1
fi

if [ -n "$codex_home" ]; then
  "$installed_aec" uninstall --codex-home "$codex_home"
else
  "$installed_aec" uninstall
fi

rm -f -- "$installed_aec"
rm -f -- "$script_path"
EOF
} >"$uninstaller_temporary"
chmod 0755 "$uninstaller_temporary"
sh -n "$uninstaller_temporary"

needs_binary_install=true
if [ -f "$target" ] && [ -x "$target" ] && cmp -s "$artifact" "$target"; then
  needs_binary_install=false
fi
needs_uninstaller_install=true
if [ -f "$uninstaller" ] && cmp -s "$uninstaller_temporary" "$uninstaller"; then
  needs_uninstaller_install=false
fi

if [ "$needs_binary_install" = true ]; then
  mkdir -p -- "$install_dir"
  binary_temporary=$(mktemp "$install_dir/.aec.XXXXXX")
  cp -- "$artifact" "$binary_temporary"
  chmod 0755 "$binary_temporary"
  cmp -s "$artifact" "$binary_temporary"
  "$binary_temporary" version >/dev/null
  mv -f -- "$binary_temporary" "$target"
  binary_temporary=
  printf 'installed %s\n' "$target"
fi

if [ "$needs_uninstaller_install" = true ]; then
  mv -f -- "$uninstaller_temporary" "$uninstaller"
  uninstaller_temporary=
  printf 'installed %s\n' "$uninstaller"
fi

if [ "$needs_binary_install" = false ] && [ "$needs_uninstaller_install" = false ]; then
  printf 'unchanged %s\n' "$target"
fi

trap - 0 HUP INT TERM
