# Install the built Windows x64 executable for the current user. This script
# deliberately does not change PATH, PowerShell policy, or Codex configuration.
[CmdletBinding()]
param([string]$InstallDir)

$ErrorActionPreference = 'Stop'

if ($args.Count -ne 0) {
    throw 'Usage: ./scripts/install-win-x64.ps1 [-InstallDir ABSOLUTE_DIRECTORY]'
}

$runningOnWindows = [System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform(
    [System.Runtime.InteropServices.OSPlatform]::Windows)
$isX64 = [System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture -eq [System.Runtime.InteropServices.Architecture]::X64
if (-not $runningOnWindows -or -not $isX64) {
    throw 'This installer supports only Windows on x64.'
}

if (-not $PSBoundParameters.ContainsKey('InstallDir')) {
    if ([string]::IsNullOrWhiteSpace($env:LOCALAPPDATA)) {
        throw 'LOCALAPPDATA is required when -InstallDir is omitted.'
    }
    $InstallDir = Join-Path $env:LOCALAPPDATA 'Programs\AEC'
}

# A drive-relative path such as C:tools is not an absolute install location.
# This first Windows slice accepts local drive paths only; UNC installs would
# need separate filesystem and cleanup validation.
if ([string]::IsNullOrWhiteSpace($InstallDir) -or
    $InstallDir -notmatch '^[A-Za-z]:[\\/]') {
    throw "-InstallDir must be an absolute local Windows path: $InstallDir"
}
$InstallDir = [System.IO.Path]::GetFullPath($InstallDir)

function Assert-OrdinaryFileOrMissing([string]$Path, [string]$Label) {
    $entry = Get-Item -LiteralPath $Path -Force -ErrorAction SilentlyContinue
    if ($null -ne $entry -and
        (($entry.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0 -or
         $entry -isnot [System.IO.FileInfo])) {
        throw "$Label must be absent or an ordinary file: $Path"
    }
}

# A junction or symlink in the chosen directory could redirect installation
# outside the path the user approved, so reject every existing linked ancestor.
$ancestor = $InstallDir
while ($null -ne $ancestor) {
    $entry = Get-Item -LiteralPath $ancestor -Force -ErrorAction SilentlyContinue
    if ($null -ne $entry -and
        ($entry.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0) {
        throw "Install path contains a linked directory: $ancestor"
    }
    $parent = [System.IO.Path]::GetDirectoryName($ancestor)
    if ($null -eq $parent -or
        [string]::Equals($parent, $ancestor, [System.StringComparison]::OrdinalIgnoreCase)) {
        break
    }
    $ancestor = $parent
}

$repoRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path
$artifact = Join-Path $repoRoot 'artifacts/aec-win-x64/aec.exe'
$target = Join-Path $InstallDir 'aec.exe'
$uninstaller = Join-Path $PSScriptRoot 'uninstall-aec-win-x64.ps1'
$marker = '# AEC generated Windows uninstaller version=1'

Assert-OrdinaryFileOrMissing $artifact 'Build artifact'
if (-not (Test-Path -LiteralPath $artifact -PathType Leaf)) {
    throw "Build artifact is missing: $artifact. Run build-win-x64.ps1 first."
}
& $artifact version | Out-Null
if ($LASTEXITCODE -ne 0) {
    throw "Build artifact failed its version check: $artifact"
}

Assert-OrdinaryFileOrMissing $target 'Install target'
Assert-OrdinaryFileOrMissing $uninstaller 'Generated uninstaller'
if (Test-Path -LiteralPath $uninstaller -PathType Leaf) {
    $firstLine = Get-Content -LiteralPath $uninstaller -TotalCount 1
    if ($firstLine -cne $marker) {
        throw "Refusing to overwrite a non-AEC uninstaller: $uninstaller"
    }
}

# The digest is an equality guard for this one installation, not a claim that
# binaries built on different machines have the same hash. The generated
# uninstaller checks it before executing or deleting this exact installed file.
$artifactHash = (Get-FileHash -LiteralPath $artifact -Algorithm SHA256).Hash
$escapedTarget = $target.Replace("'", "''")
$escapedUninstaller = $uninstaller.Replace("'", "''")
$uninstallerText = @'
# AEC generated Windows uninstaller version=1
# Generated by install-win-x64.ps1. Do not edit this managed helper.
[CmdletBinding()]
param([string]$CodexHome)

$ErrorActionPreference = 'Stop'
$installedAec = '__AEC_TARGET__'
$expectedHash = '__AEC_HASH__'
$expectedHelper = '__AEC_HELPER__'

if ($args.Count -ne 0) {
    throw 'Usage: ./scripts/uninstall-aec-win-x64.ps1 [-CodexHome ABSOLUTE_PATH]'
}
if (-not [string]::Equals(
        [System.IO.Path]::GetFullPath($PSCommandPath), $expectedHelper,
        [System.StringComparison]::OrdinalIgnoreCase)) {
    throw 'Run the generated uninstaller from its original location.'
}
if ($PSBoundParameters.ContainsKey('CodexHome') -and
    ($CodexHome -notmatch '^(?:[A-Za-z]:[\\/]|\\\\[^\\/]+[\\/][^\\/]+(?:[\\/]|$))')) {
    throw "-CodexHome must be an absolute Windows path: $CodexHome"
}

$entry = Get-Item -LiteralPath $installedAec -Force -ErrorAction SilentlyContinue
if ($null -eq $entry -or $entry -isnot [System.IO.FileInfo] -or
    ($entry.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0) {
    throw "Installed aec.exe is missing or unsafe: $installedAec"
}
if ((Get-FileHash -LiteralPath $installedAec -Algorithm SHA256).Hash -cne $expectedHash) {
    throw "Installed aec.exe differs from the recorded build: $installedAec"
}

# Runtime integration must be removed before the executable or helper. AEC
# preserves the selected data repository and runtime config.toml itself.
if ($PSBoundParameters.ContainsKey('CodexHome')) {
    & $installedAec uninstall --codex-home $CodexHome
} else {
    & $installedAec uninstall
}
if ($LASTEXITCODE -ne 0) {
    throw "aec uninstall failed; leaving executable and helper in place."
}

Remove-Item -LiteralPath $installedAec -Force
Remove-Item -LiteralPath $PSCommandPath -Force
'@
$uninstallerText = $uninstallerText.Replace('__AEC_HASH__', $artifactHash)
$uninstallerText = $uninstallerText.Replace('__AEC_HELPER__', $escapedUninstaller)
$uninstallerText = $uninstallerText.Replace('__AEC_TARGET__', $escapedTarget)

# Parse before changing either output, and write the helper beside its final
# location so the final rename is atomic on the same volume.
$tokens = $null
$parseErrors = $null
$null = [System.Management.Automation.Language.Parser]::ParseInput(
    $uninstallerText, [ref]$tokens, [ref]$parseErrors)
if ($parseErrors.Count -ne 0) {
    throw "Generated uninstaller did not parse: $($parseErrors[0])"
}
$uninstallerTemporary = Join-Path $PSScriptRoot ('.uninstall-aec-' + [guid]::NewGuid().ToString('N') + '.tmp')
$binaryTemporary = $null
try {
    [System.IO.File]::WriteAllText(
        $uninstallerTemporary, $uninstallerText,
        [System.Text.UTF8Encoding]::new($false))

    $binaryNeedsInstall = -not (Test-Path -LiteralPath $target -PathType Leaf) -or
        (Get-FileHash -LiteralPath $target -Algorithm SHA256).Hash -cne $artifactHash
    $helperNeedsInstall = -not (Test-Path -LiteralPath $uninstaller -PathType Leaf) -or
        [System.IO.File]::ReadAllText($uninstaller) -cne $uninstallerText

    if ($binaryNeedsInstall) {
        $null = New-Item -ItemType Directory -Path $InstallDir -Force
        $binaryTemporary = Join-Path $InstallDir ('.aec-' + [guid]::NewGuid().ToString('N') + '.exe')
        [System.IO.File]::Copy($artifact, $binaryTemporary)
        if ((Get-FileHash -LiteralPath $binaryTemporary -Algorithm SHA256).Hash -cne $artifactHash) {
            throw 'Copied executable differs from the build artifact.'
        }
        & $binaryTemporary version | Out-Null
        if ($LASTEXITCODE -ne 0) {
            throw 'Copied executable failed its version check.'
        }
        if (Test-Path -LiteralPath $target -PathType Leaf) {
            # Move the verified sibling over the old executable without a backup path.
            [System.IO.File]::Move($binaryTemporary, $target, $true)
        } else {
            [System.IO.File]::Move($binaryTemporary, $target)
        }
        $binaryTemporary = $null
        Write-Output "installed $target"
    }

    if ($helperNeedsInstall) {
        if (Test-Path -LiteralPath $uninstaller -PathType Leaf) {
            [System.IO.File]::Move($uninstallerTemporary, $uninstaller, $true)
        } else {
            [System.IO.File]::Move($uninstallerTemporary, $uninstaller)
        }
        $uninstallerTemporary = $null
        Write-Output "installed $uninstaller"
    }

    if (-not $binaryNeedsInstall -and -not $helperNeedsInstall) {
        Write-Output "unchanged $target"
    }
} finally {
    if ($null -ne $binaryTemporary -and (Test-Path -LiteralPath $binaryTemporary)) {
        Remove-Item -LiteralPath $binaryTemporary -Force
    }
    if ($null -ne $uninstallerTemporary -and (Test-Path -LiteralPath $uninstallerTemporary)) {
        Remove-Item -LiteralPath $uninstallerTemporary -Force
    }
}

# Codex can inherit a different PATH from this shell. Never rewrite user PATH
# here; tell the user to expose this folder and restart Codex before using $aec.
$currentPathDirectories = @($env:PATH -split ';' | ForEach-Object { $_.Trim('"').TrimEnd('\') })
if (-not ($currentPathDirectories -contains $InstallDir.TrimEnd('\'))) {
    Write-Warning "Add $InstallDir to your user PATH, restart Codex, then run aec help."
} else {
    Write-Output "Ensure Codex inherits $InstallDir in PATH; restart Codex if needed."
}
